application: hackillinois
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /assets
  static_dir: assets

- url: /sponsor(s?)(/?)
  static_files: assets/HackIllinois Sponsorship.pdf
  upload: assets/HackIllinois Sponsorship\.pdf

- url: /sponsor(s?)/startup(/?)
  static_files: assets/special_sponsorship/HackIllinois Startup.pdf
  upload: assets/special_sponsorship/HackIllinois Startup\.pdf

- url: /sponsor(s?)/api(/?)
  static_files: assets/special_sponsorship/HackIllinois API.pdf
  upload: assets/special_sponsorship/HackIllinois API\.pdf

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest