# There's no need to change this app ID anymore to push to dev! See the "Git Deploy Setup Guide" in README.md
application: hackillinois-dev
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /img/logos/resized
  static_dir: assets/logos/resized

- url: /img/logos
  static_dir: assets/logos

- url: /img
  static_dir: assets/img

- url: /assets
  static_dir: assets

- url: /sponsor(s?)(/?)
  static_files: assets/docs/HackIllinois Sponsorship.pdf
  upload: assets/docs/HackIllinois Sponsorship\.pdf

- url: /sponsor(s?)/startup(s?)(/?)
  static_files: assets/docs/special_sponsorship/HackIllinois Startup.pdf
  upload: assets/docs/special_sponsorship/HackIllinois Startup\.pdf

- url: /sponsor(s?)/api(/?)
  static_files: assets/docs/special_sponsorship/HackIllinois API.pdf
  upload: assets/docs/special_sponsorship/HackIllinois API\.pdf

- url: /sponsor(s?)/vc(s?)(/?)
  static_files: assets/docs/special_sponsorship/HackIllinois VC.pdf
  upload: assets/docs/special_sponsorship/HackIllinois VC\.pdf

- url: /register*
  script: main.app
  login: required

- url: /profile*
  script: main.app
  login: required

- url: /admin/approve
  script: main.app
  login: admin

- url: /admin*
  script: main.app
  login: admin

# - url: /_ah/login_required
#   script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest