# There's no need to change this app ID anymore to push to dev! See the "Git Deploy Setup Guide" in README.md
# Again: DO NOT CHANGE THIS APP ID FROM "hackillinois"
application: hackillinois
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10m"
instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: /favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots\.txt

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

- url: /img/logos/resized
  static_dir: assets/logos/resized

- url: /img/logos
  static_dir: assets/logos

- url: /img/og_logo.png
  static_files: assets/img/opengraph_logo.png
  upload: assets/img/opengraph_logo\.jpg

- url: /img
  static_dir: assets/img

- url: /lib
  static_dir: assets/lib/

- url: /assets
  static_dir: assets

- url: /sponsor(s?)(/?)
  static_files: assets/docs/HackIllinois Sponsorship.pdf
  upload: assets/docs/HackIllinois Sponsorship\.pdf

- url: /sponsor(s?)/startup(s?)(/?)
  static_files: assets/docs/special_sponsorship/HackIllinois Startup.pdf
  upload: assets/docs/special_sponsorship/HackIllinois Startup\.pdf

- url: /sponsor(s?)/api(/?)
  static_files: assets/docs/special_sponsorship/HackIllinois API.pdf
  upload: assets/docs/special_sponsorship/HackIllinois API\.pdf

- url: /sponsor(s?)/vc(s?)(/?)
  static_files: assets/docs/special_sponsorship/HackIllinois VC.pdf
  upload: assets/docs/special_sponsorship/HackIllinois VC\.pdf

- url: /apply.*
  script: main.app
  login: required

- url: /rsvp.*
  script: main.app
  login: required

- url: /admin.*
  script: main.app
  login: required

- url: /corporate.*
  script: main.app
  login: required

- url: /research.*
  script: main.app
  login: required

# https://developers.google.com/appengine/articles/python/recording_exceptions_with_ereporter
- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

# https://developers.google.com/appengine/docs/python/tools/appstats?csw=1
builtins:
- appstats: on
- remote_api: on
- deferred: on

inbound_services:
- warmup